development:
  adapter: postgresql
  encoding: unicode
  database: who-was-i_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: who-was-i_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: who-was-i_production
  pool: 5
